---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Home"
subtitle: "DigtialAdapt"
logo: "assets/icons/apple-touch-icon.png" ## "logo.png"
#icon: "fas fa-home" # Optional icon

header: true
footer: false #'<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: andrew

stylesheet:
  - "/assets/custom.css"

colors:
  light:
    highlight-primary: "#af87ba" ## badger purple tie color ## "#4acaa8" # "#3367d6"
    highlight-secondary: "#9d79a7" ## one shade darker, color-hex.com ## "#3aba98" # "#4285f4"
    highlight-hover: "#b793c0" ## one shade lighter, color-hex.com ## "#2aaa88" # "#5a95f5"
    background: "#1f2d50" ## my tardis blue ## "#f5f5f5"
    card-background: "#354261" ## one shade lighter, color-hex.com ## "#ffffff"
    text: "#eeeeee" ## website text color ## "#363636"
    text-header: "#1f2d50" ## my tardis blue ## "#ffffff"
    text-title: "#aaa" ## website light text color ## "#303030"
    text-subtitle: "#eeeeee" ## website text color ## "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#af87ba" ## badger purple tie color ## "#363636"
#  dark:
#    highlight-primary: "#4acaa8" # "#3367d6"
#    highlight-secondary: "#3aba98" # "#4285f4"
#    highlight-hover: "#2aaa88" # "#5a95f5"
#    background: "#131313"
#    card-background: "#2b2b2b"
#    text: "#eaeaea"
#    text-header: "#ffffff"
#    text-title: "#fafafa"
#    text-subtitle: "#f5f5f5"
#    card-shadow: rgba(0, 0, 0, 0.4)
#    link-hover: "#ffdd57"

# Optional message
message:
  url: "https://cyber.digitaladapt.com/motd.php"
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  icon: "fa fa-grin"
#  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Facebook"
    icon: "fab fa-facebook"
    url: "https://www.facebook.com/andrew.backe.stowell"
    target: "_blank"
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/digitaladapt"
    target: "_blank"
#  - name: "Bitbucket"
#    icon: "fab fa-bitbucket"
#    url: "https://bitbucket.org/digitaladapt"
#    target: "_blank"
  - name: "Instagram"
    icon: "fab fa-instagram"
    url: "https://www.instagram.com/digitaladapt"
    target: "_blank"
  - name: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/digitaladapt"
    target: "_blank"
  - name: "Reddit"
    icon: "fab fa-reddit"
    url: "https://www.reddit.com/u/digitaladapt"
    target: "_blank"
  - name: "Mastodon"
    icon: "fab fa-mastodon"
    url: "https://toot.community/@digitaladapt"
    target: "_blank"
  - name: "Keybase"
    icon: "fab fa-keybase"
    url: "https://keybase.io/digitaladapt"
    target: "_blank"
  - name: "Discord"
    icon: "fab fa-discord"
    url: "https://discord.com/users/570971366833127425"
    target: "_blank"
  - name: "Twitter"
    icon: "fab fa-twitter"
    url: "https://twitter.com/digitaladapt"
    target: "_blank"
  - name: "Mail"
    icon: "fas fa-envelope"
    url: "mailto:andrew@digitaladapt.com"
    target: "_blank"

#  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
#  # see url field and assets/additionnal-page.yml.dist used in this example:
#  - name: "another page!"
#    icon: "fas fa-file-alt"
#    url: "#additionnal-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Weather"
        location: "Radford"
        locationId: "4780837" # city-id
        apiKey: "3053209dc8d71884daaaf1f7f4e1d290"
        units: "imperial" # "metric", "imperial", or "kelvin"
        background: "circle" # "square", "cicle", or "none"
        type: "OpenWeather"
      - name: "Email"
        logo: "/assets/logos/zoho-mail.png"
        #icon: "fas fa-envelope"
        subtitle: "Zoho Mail"
        tag: "email"
        url: "https://mail.zoho.com/"
      - name: "Web Host"
        logo: "/assets/logos/digital-ocean.svg"
        #icon: "fab fa-digital-ocean"
        subtitle: "Digtial Ocean"
        tag: "cloud"
        url: "https://cloud.digitalocean.com/"
      - name: "AdGuard"
        type: "AdGuardHome"
        logo: "/assets/logos/ad-guard.png"
        #icon: "fas fa-shield-alt"
        tag: "defense"
        url: "https://dalek.digitaladapt.com/"
        useCredentials: true
      - name: "Nextcloud"
        logo: "/assets/logos/whale.svg"
        subtitle: "DigitalAdapt Tardis"
        tag: "files"
        url: "https://tardis.digitaladapt.com/"
  - name: "Finances"
    icon: "fas fa-coins"
    items:
      - name: "American Express"
        logo: "/assets/logos/american-express.svg"
        #icon: "fab fa-cc-amex"
        subtitle: ""
        tag: "credit"
        url: "https://www.americanexpress.com/"
      - name: "Bank of America"
        logo: "/assets/logos/bank-of-america.png"
        #icon: "fab fa-cc-mastercard"
        subtitle: ""
        tag: "credit"
        url: "https://www.bankofamerica.com/"
      - name: "Chase Bank"
        logo: "/assets/logos/chase.png"
        #icon: "fab fa-cc-visa"
        subtitle: ""
        tag: "credit"
        url: "https://www.chase.com/"
      - name: "Discover Card"
        logo: "/assets/logos/discover-card.png"
        #icon: "fab fa-cc-discover"
        subtitle: ""
        tag: "credit"
        url: "https://www.discover.com/"
      - name: "IKEA Project Card"
        logo: "/assets/logos/ikea.svg"
        #icon: "fab fa-cc-visa"
        subtitle: "Comenity"
        tag: "credit"
        url: "https://d.comenity.net/ikeaprojekt/"
      - name: "VyStar Credit Union"
        logo: "/assets/logos/vystar.png"
        #icon: "fas fa-crosshairs"
        tag: "bank"
        url: "https://vystarcu.org/"
      - name: "NCSECU"
        logo: "/assets/logos/ncsecu.png"
        #icon: "fas fa-money-bill"
        subtitle: "North Carolina State Employees Credit Union"
        tag: "bank"
        url: "https://www.ncsecu.org/"
  - name: "Work"
    icon: "fas fa-briefcase"
    items:
      - name: "Maplight Github"
        logo: "/assets/logos/github.png"
        #icon: "fab fa-github"
        subtitle: ""
        tag: "maplight"
        url: "https://github.com/maplight"
      - name: "Maplight BitBucket"
        logo: "/assets/logos/bitbucket.svg"
        #icon: "fab fa-bitbucket"
        subtitle: ""
        tag: "maplight"
        url: "https://bitbucket.org/maplight/"
      - name: "Maplight Tech BitBucket"
        logo: "/assets/logos/bitbucket.svg"
        #icon: "fab fa-bitbucket"
        subtitle: ""
        tag: "maplight"
        url: "https://bitbucket.org/maplighttech/"
      - name: "Maplight Confluence"
        logo: "/assets/logos/confluence.svg"
        #icon: "fab fa-confluence"
        subtitle: ""
        tag: "maplight"
        url: "https://maplight.atlassian.net/wiki/home"
      - name: "Maplight Jira"
        logo: "/assets/logos/jira.svg"
        #icon: "fab fa-jira"
        subtitle: ""
        tag: "maplight"
        url: "https://maplight.atlassian.net/jira"
      - name: "Voters Edge Trello"
        logo: "/assets/logos/trello.svg"
        #icon: "fab fa-trello"
        subtitle: ""
        tag: "maplight"
        url: "https://trello.com/b/v5IsvK5e/votersedge"
      - name: "Maplight AWS Console"
        logo: "/assets/logos/aws.png"
        #icon: "fab fa-aws"
        subtitle: ""
        tag: "maplight"
        url: "https://console.aws.amazon.com/"
#  - name: "Crypto"
#    icon: "fab fa-bitcoin"
#    items:
#      - name: "Loop Markets"
#        logo: "/assets/logos/loop.png"
#        subtitle: "Terra"
#        tag: "crypto"
#        url: "https://www.loop.markets/community/"
#      - name: "Anchor Protocol"
#        logo: "/assets/logos/anchor-protocol.png"
#        #icon: "fas fa-anchor"
#        subtitle: "Terra"
#        tag: "crypto"
#        url: "https://app.anchorprotocol.com/"
#      - name: "Pylon App"
#        logo: "/assets/logos/pylon-protocol.png"
#        #icon: "fab fa-buffer"
#        subtitle: "Terra"
#        tag: "crypto"
#        url: "https://app.pylon.money/"
#      - name: "Pylon Gateway"
#        logo: "/assets/logos/pylon-protocol.png"
#        #icon: "fas fa-dungeon"
#        subtitle: "Terra"
#        tag: "crypto"
#        url: "https://gateway.pylon.money/"
#      - name: "TerraSwap"
#        logo: "/assets/logos/terra-swap.png"
#        #icon: "fas fa-exchange-alt"
#        subtitle: "Terra"
#        tag: "crypto"
#        url: "https://app.terraswap.io/"
#      - name: "Nexus Protocol"
#        logo: "/assets/logos/nexus-protocol.png"
#        #icon: "fas fa-expand-arrows-alt"
#        subtitle: "Terra"
#        tag: "crypto"
#        url: "https://terra.nexusprotocol.app/"
#      - name: "Terra World"
#        logo: "/assets/logos/terra-world.png"
#        #icon: "fas fa-globe"
#        subtitle: "Terra"
#        tag: "crypto"
#        url: "https://app.terraoffice.world/"
#      - name: "ThorSwap"
#        logo: "/assets/logos/thor-swap.png"
#        #icon: "fas fa-bolt"
#        subtitle: "ThorChain"
#        tag: "crypto"
#        url: "https://app.thorswap.finance/"
#      - name: "KuCoin"
#        logo: "/assets/logos/kucoin.png"
#        #icon: "fas fa-hand-holding-usd"
#        subtitle: ""
#        tag: "crypto"
#        url: "https://www.kucoin.com/"
#      - name: ""
#        icon: ""
#        subtitle: ""
#        tag: ""
#        url: ""
