---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Home"
subtitle: "DigtialAdapt"
logo: "assets/icons/apple-touch-icon.png" ## "logo.png"
#icon: "fas fa-home" # Optional icon

header: true
footer: false #'<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: andrew

stylesheet:
  - "/assets/custom.css"

colors:
  light:
    highlight-primary: "#af87ba" ## badger purple tie color ## "#4acaa8" # "#3367d6"
    highlight-secondary: "#9d79a7" ## one shade darker, color-hex.com ## "#3aba98" # "#4285f4"
    highlight-hover: "#b793c0" ## one shade lighter, color-hex.com ## "#2aaa88" # "#5a95f5"
    background: "#1f2d50" ## my tardis blue ## "#f5f5f5"
    card-background: "#354261" ## one shade lighter, color-hex.com ## "#ffffff"
    text: "#eeeeee" ## website text color ## "#363636"
    text-header: "#1f2d50" ## my tardis blue ## "#ffffff"
    text-title: "#aaa" ## website light text color ## "#303030"
    text-subtitle: "#eeeeee" ## website text color ## "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#af87ba" ## badger purple tie color ## "#363636"
#  dark:
#    highlight-primary: "#4acaa8" # "#3367d6"
#    highlight-secondary: "#3aba98" # "#4285f4"
#    highlight-hover: "#2aaa88" # "#5a95f5"
#    background: "#131313"
#    card-background: "#2b2b2b"
#    text: "#eaeaea"
#    text-header: "#ffffff"
#    text-title: "#fafafa"
#    text-subtitle: "#f5f5f5"
#    card-shadow: rgba(0, 0, 0, 0.4)
#    link-hover: "#ffdd57"

# Optional message
message:
  url: "/motd.php"
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  icon: "fa fa-grin"
#  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Facebook"
    icon: "fab fa-facebook"
    url: "https://www.facebook.com/andrew.backe.stowell"
    target: "_blank"
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/digitaladapt"
    target: "_blank"
#  - name: "Bitbucket"
#    icon: "fab fa-bitbucket"
#    url: "https://bitbucket.org/digitaladapt"
#    target: "_blank"
  - name: "Instagram"
    icon: "fab fa-instagram"
    url: "https://www.instagram.com/digitaladapt"
    target: "_blank"
  - name: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/digitaladapt"
    target: "_blank"
  - name: "Reddit"
    icon: "fab fa-reddit"
    url: "https://www.reddit.com/u/digitaladapt"
    target: "_blank"
  - name: "Mastodon"
    icon: "fab fa-mastodon"
    url: "https://toot.community/@digitaladapt"
    target: "_blank"
  - name: "Keybase"
    icon: "fab fa-keybase"
    url: "https://keybase.io/digitaladapt"
    target: "_blank"
  - name: "Discord"
    icon: "fab fa-discord"
    url: "https://discord.com/users/570971366833127425"
    target: "_blank"
  - name: "Twitter"
    icon: "fab fa-twitter"
    url: "https://twitter.com/digitaladapt"
    target: "_blank"
  - name: "Mail"
    icon: "fas fa-envelope"
    url: "mailto:andrew@digitaladapt.com"
    target: "_blank"

#  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
#  # see url field and assets/additionnal-page.yml.dist used in this example:
#  - name: "another page!"
#    icon: "fas fa-file-alt"
#    url: "#additionnal-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Weather"
    icon: "fas fa-cloud"
    items:
      - name: "Weather"
        location: "Radford"
        locationId: "4780837" # city-id
        apiKey: "3053209dc8d71884daaaf1f7f4e1d290"
        units: "imperial" # "metric", "imperial", or "kelvin"
        background: "circle" # "square", "cicle", or "none"
        type: "OpenWeather"
  - name: "GnomeCoder"
    logo: "https://gnomecoder.com/favicon.ico"
    items:
      - name: "GnomeCoder Website"
        subtitle: "Informal Blog"
        tag: "gnome"
        url: "https://gnomecoder.com/"
      - name: "Stats for GnomeCoder"
        subtitle: "Usage Statistics"
        tag: "usage"
        url: "https://stats.gnomecoder.com/"
  - name: "TheDataKnit"
    logo: "https://www.thedataknit.com/favicon.ico"
    items:
      - name: "Stats for TheDataKnit"
        subtitle: "Usage Statistics"
        tag: "usage"
        url: "https://stats.thedataknit.com/"
      - name: "TheDataKnit Website"
        subtitle: "Landing page for my wife"
        tag: "landing"
        url: "https://www.thedataknit.com/"
  - name: "DigitalAdapt"
    logo: "https://digitaladapt.com/favicon.ico"
    items:
      - name: "DigitalAdapt Website"
        subtitle: "Portfolio, CV, Resume"
        tag: "portfolio"
        url: "https://digitaladapt.com/"
      - name: "Sif DNS Instance"
        subtitle: "AdGuardHome"
        tag: "dns"
        url: "https://sif.digitaladapt.com/"
        type: "AdGuardHome"
        useCredentials: true
      - name: "Tyr DNS Instance"
        subtitle: "AdGuardHome"
        tag: "dns"
        url: "https://tyr.digitaladapt.com/"
        type: "AdGuardHome"
        useCredentials: true
      - name: "Home for DigitalAdapt"
        subtitle: "(you are here)"
        tag: "links"
        url: "https://home.digitaladapt.com/"
      - name: "Logging for DigitalAdapt"
        subtitle: "A place to log events"
        tag: "logging"
        url: "https://log.digitaladapt.com/"
      - name: "Map of Continents"
        subtitle: "custom projection to preserve land size and shape"
        tag: "map"
        url: "https://map.digitaladapt.com/"
      - name: "Preview for DigtitalAdapt"
        subtitle: "tentative changes show up here, before being deployed"
        tag: "dev"
        url: "https://preview.digitaladapt.com/"
      - name: "GitHub Stats - Overview"
        subtitle: "Stars, PRs, etc"
        tag: "git"
        url: "https://readme.digitaladapt.com/?username=digitaladapt"
      - name: "GitHub Stats - Languages"
        subtitle: "Top Programming Languages"
        tag: "git"
        url: "https://readme.digitaladapt.com/top-langs/?username=digitaladapt"
      - name: "Stats for DigitalAdapt"
        subtitle: "Usage Statistics"
        tag: "usage"
        url: "https://stats.digitaladapt.com/"
      - name: "Website Theme"
        subtitle: "An HTML5 UP! theme implemented in Jekyll"
        tag: "theme"
        url: "https://theme.digitaladapt.com/"
      - name: "Public Files"
        subtitle: "mostly just .ics calendar files"
        tag: "files"
        url: "https://vortex.digitaladapt.com/"
      - name: "Operations Status"
        subtitle: "is it down?"
        tag: "status"
        url: "https://status.digitaladapt.com/"
      - name: "Nextcloud"
        subtitle: "It's bigger on the inside"
        tag: "files"
        url: "https://tardis.digitaladapt.com"
